export const initialUserState = {
  username: "",
  password: "",
  confirmPassword: "",
  contract: "fullTime",
  role: "user",
  operations: "",
  trainer: "",
  driver: "",
  navigator: "",
  temp: "",
  certified: "false",
  injured: "false",
  joinDate: "10/10/2010",
  location: "",
  rosterMonday: "unselected",
  rosterTuesday: "unselected",
  rosterWednesday: "unselected",
  rosterThursday: "unselected",
  rosterFriday: "unselected",
  rosterSaturday: "unselected",
  employeeType: []
}